baseURL = "/api5/documentation/techdocs/"
languageCode = "en-us"
title = "Booka Users Documentation"

# directories
archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "../app/api5/documentation/techdocs"
staticDir = "static"
themesDir = "themes"


[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.shortcuts]]
name = "<i class='fa faw fa-bitbucket'></i> Bitbucket Repository"
url = "https://bitbucket.org/booka-app/booka-documentation"
weight = 10

[params]
themeVariant = "mine"
